-- ============================================================
-- Script 03: Staging & Transformation
-- Project  : SA Retail Bank Customer Churn Analysis
-- Author   : Dominic Dandajena
-- Description:
--   Transforms the three raw source tables into clean,
--   typed, and enriched staging tables. Every cleaning
--   decision applied here is based on the DQ findings
--   documented in Script 02.
--
--   Three staging tables are produced:
--   staging.customers — cleaned demographics and derived
--                       customer attributes
--   staging.products  — standardised product holdings
--                       with validity flags
--   staging.activity  — cleaned behavioural and financial
--                       data with derived risk attributes
--
--   The staging layer is designed as a reusable, general
--   purpose data layer. The wide analytical table used
--   by Power BI is assembled separately in Script 05,
--   keeping the staging architecture independent of any
--   specific reporting requirement.
--
--   Orphan records, duplicate CustomerIDs, and invalid
--   reference data are resolved here. All flags applied
--   are additive — no source records are deleted. Exclusion
--   logic is applied at the analytical table layer in
--   Script 05, preserving the full audit trail here.
--
-- Date Reference:
--   All date calculations use the dataset reference date
--   of 2024-12-31, representing present day within the
--   bank's timeline.
-- ============================================================

USE BankChurnAnalysis;
GO

-- ============================================================
-- SECTION 1: STAGING.CUSTOMERS
-- ============================================================

IF OBJECT_ID('staging.customers', 'U') IS NOT NULL
    DROP TABLE staging.customers;

-- Deduplication is applied first and fed into all subsequent
-- CTEs to ensure the entire transformation chain operates
-- on deduplicated data. Building province_mapping directly
-- from raw.customers would allow duplicate CustomerIDs to
-- survive through the join, as the mapping CTE would match
-- both the original and duplicate row on customer_id.
-- By sourcing province_mapping from the deduplication CTE
-- with row_num = 1 applied, this is prevented entirely.
--
-- Deduplication uses ROW_NUMBER partitioned by customer_id,
-- ordered by monthly_income ASC. The duplicate row was
-- generated by applying a 5% uplift to the original income
-- value, making the lower value reliably the original record
-- across all 30 duplicate pairs. See DQ-03b in Script 02
-- for the full investigation and reasoning.
--
-- Province mapping standardises 26 raw variants to 9 clean
-- province names. UPPER and TRIM to handle casing 
-- differences and whitespace irregularities
-- from the source system before the comparison is made.
--
-- Gender is standardised to Male/Female. Branch code
-- JHB-CBD is expanded to its full name for consistency
-- with the naming convention of all other branch codes.
--
-- Join dates beyond the dataset reference date of 2024-12-31
-- are flagged with is_valid_join_date = 0 and excluded from
-- tenure calculations. The customer record is retained
-- as the activity data remains analytically valid.
--
-- Null account statuses are imputed as Unknown rather than
-- dropping the row. Account status is business critical for
-- segmentation but losing customers over a single missing
-- field is not justified at this dataset size.
--
-- Monthly income is cast to INT via a FLOAT intermediate
-- step. The source system stored income as a decimal string
-- (e.g. "35000.0") which causes a direct INT conversion to
-- return NULL for every value. The FLOAT step handles the
-- decimal representation before the final INT cast.
--
-- Derived columns added in staging:
--   age          — calculated from DOB against 2024-12-31
--   age_band     — segmentation bands for analysis
--   tenure_days  — days between join date and 2024-12-31
--   tenure_band  — segmentation bands for analysis
--   income_tier  — segmentation bands aligned to SA retail
--                  banking income segments
--
-- Sort order for band columns is handled in the Power BI
-- layer via DAX calculated columns. Numeric prefixes are
-- deliberately excluded from band values to keep the SQL
-- layer free of presentation logic.

WITH deduplication AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY customer_id
            ORDER BY TRY_CONVERT(FLOAT, monthly_income) ASC
        ) AS row_num
    FROM raw.customers
),

province_mapping AS (
    SELECT
        customer_id,
        CASE
            WHEN UPPER(LTRIM(RTRIM(province))) IN ('GAUTENG', 'GP', 'GUATENG')
                THEN 'Gauteng'
            WHEN UPPER(LTRIM(RTRIM(province))) IN ('KWAZULU-NATAL', 'KZN',
                'KWAZULU NATAL')
                THEN 'KwaZulu-Natal'
            WHEN UPPER(LTRIM(RTRIM(province))) IN ('WESTERN CAPE', 'WC',
                'W CAPE')
                THEN 'Western Cape'
            WHEN UPPER(LTRIM(RTRIM(province))) IN ('EASTERN CAPE', 'EC',
                'E CAPE')
                THEN 'Eastern Cape'
            WHEN UPPER(LTRIM(RTRIM(province))) IN ('LIMPOPO', 'LP', 'LIMPOP')
                THEN 'Limpopo'
            WHEN UPPER(LTRIM(RTRIM(province))) IN ('MPUMALANGA', 'MP')
                THEN 'Mpumalanga'
            WHEN UPPER(LTRIM(RTRIM(province))) IN ('NORTH WEST', 'NW',
                'N WEST')
                THEN 'North West'
            WHEN UPPER(LTRIM(RTRIM(province))) IN ('FREE STATE', 'FS',
                'FREESTATE')
                THEN 'Free State'
            WHEN UPPER(LTRIM(RTRIM(province))) IN ('NORTHERN CAPE', 'NC',
                'N CAPE')
                THEN 'Northern Cape'
            ELSE 'Unknown'
        END AS province_clean
    FROM deduplication
    WHERE row_num = 1
),

base_customers AS (
    SELECT
        d.customer_id,
        d.first_name,
        d.last_name,

        -- DOB kept as DATE where parseable, NULL otherwise.
        -- Null DOB is handled by the downstream
        -- age and age_band calculations returning NULL and
        -- Unknown respectively.
        TRY_CONVERT(DATE, d.date_of_birth)              AS date_of_birth,

        -- Gender standardised to Male/Female.
        -- UPPER and TRIM applied before comparison.
        CASE
            WHEN UPPER(LTRIM(RTRIM(d.gender))) IN ('M', 'MALE')   THEN 'Male'
            WHEN UPPER(LTRIM(RTRIM(d.gender))) IN ('F', 'FEMALE') THEN 'Female'
            ELSE 'Unknown'
        END                                              AS gender,

        -- Province standardised via mapping CTE
        p.province_clean                                 AS province,

        -- Branch code: JHB-CBD expanded to full name for
        -- consistency with all other branch code values
        CASE
            WHEN UPPER(LTRIM(RTRIM(d.branch_code))) = 'JHB-CBD'
                THEN 'Johannesburg CBD'
            ELSE d.branch_code
        END                                              AS branch_code,

        -- Join date converted to DATE where parseable
        TRY_CONVERT(DATE, d.join_date)                  AS join_date,

        -- Join date validity flag
        -- Dates beyond the dataset reference date of
        -- 2024-12-31 are invalid within the bank's timeline
        CASE
            WHEN TRY_CONVERT(DATE, d.join_date) IS NULL         THEN 0
            WHEN TRY_CONVERT(DATE, d.join_date) > '2024-12-31'  THEN 0
            ELSE 1
        END                                              AS is_valid_join_date,

        -- Account status: nulls imputed as Unknown
        ISNULL(d.account_status, 'Unknown')             AS account_status,

        -- Monthly income cast to INT via FLOAT intermediate step.
        -- Source system stored values as decimal strings
        -- e.g. "35000.0" — direct INT conversion returns NULL.
        -- FLOAT handles the decimal representation before
        -- the final INT cast is applied.
        TRY_CONVERT(INT, TRY_CONVERT(FLOAT,
            d.monthly_income))                          AS monthly_income

    FROM deduplication d
    JOIN province_mapping p ON d.customer_id = p.customer_id
    WHERE d.row_num = 1
)

SELECT
    customer_id,
    first_name,
    last_name,
    date_of_birth,
    gender,
    province,
    branch_code,
    join_date,
    is_valid_join_date,
    account_status,
    monthly_income,

    -- Age derived from DOB against dataset reference date.
    -- NULL returned where DOB is missing or unparseable.
    CASE
        WHEN date_of_birth IS NULL THEN NULL
        ELSE DATEDIFF(YEAR, date_of_birth, '2024-12-31')
    END                                                  AS age,

    -- Age band for segmentation analysis.
    -- Unknown returned where DOB is missing.
    CASE
        WHEN date_of_birth IS NULL THEN 'Unknown'
        WHEN DATEDIFF(YEAR,
            date_of_birth, '2024-12-31') BETWEEN 18 AND 25 THEN '18-25'
        WHEN DATEDIFF(YEAR,
            date_of_birth, '2024-12-31') BETWEEN 26 AND 35 THEN '26-35'
        WHEN DATEDIFF(YEAR,
            date_of_birth, '2024-12-31') BETWEEN 36 AND 45 THEN '36-45'
        WHEN DATEDIFF(YEAR,
            date_of_birth, '2024-12-31') BETWEEN 46 AND 55 THEN '46-55'
        WHEN DATEDIFF(YEAR,
            date_of_birth, '2024-12-31') BETWEEN 56 AND 65 THEN '56-65'
        WHEN DATEDIFF(YEAR,
            date_of_birth, '2024-12-31') > 65             THEN '65+'
        ELSE 'Unknown'
    END                                                  AS age_band,

    -- Tenure in days from join date to dataset reference date.
    -- NULL returned where join date is invalid.
    CASE
        WHEN is_valid_join_date = 0 THEN NULL
        ELSE DATEDIFF(DAY, join_date, '2024-12-31')
    END                                                  AS tenure_days,

    -- Tenure band for segmentation analysis.
    -- Unknown returned where join date is invalid.
    -- Sort order handled in Power BI via DAX calculated
    -- column — numeric prefixes deliberately excluded.
    CASE
        WHEN is_valid_join_date = 0 THEN 'Unknown'
        WHEN DATEDIFF(DAY,
            join_date, '2024-12-31') < 365   THEN 'Less than 1 Year'
        WHEN DATEDIFF(DAY,
            join_date, '2024-12-31') < 730   THEN '1-2 Years'
        WHEN DATEDIFF(DAY,
            join_date, '2024-12-31') < 1825  THEN '2-5 Years'
        ELSE                                      '5+ Years'
    END                                                  AS tenure_band,

    -- Income tier for segmentation analysis.
    -- Bands aligned to South African retail banking
    -- income segments. Sort order handled in Power BI.
    CASE
        WHEN monthly_income IS NULL     THEN 'Unknown'
        WHEN monthly_income < 7000      THEN 'Below R7,000'
        WHEN monthly_income < 15000     THEN 'R7,000 - R14,999'
        WHEN monthly_income < 30000     THEN 'R15,000 - R29,999'
        WHEN monthly_income < 60000     THEN 'R30,000 - R59,999'
        ELSE                                 'R60,000 & above'
    END                                                  AS income_tier

INTO staging.customers
FROM base_customers;

-- ============================================================
-- SECTION 2: STAGING.PRODUCTS
-- ============================================================

IF OBJECT_ID('staging.products', 'U') IS NOT NULL
    DROP TABLE staging.products;

-- Product name mapping CTE standardises 20 raw variants
-- to 5 clean product names. The same UPPER/TRIM commands 
-- are applied consistently across all mapping CTEs
-- in this script to handle casing and whitespace
-- irregularities from the source system.

-- Open-date validity is assessed against two conditions:
-- dates pre-dating the bank's inception (2015-01-01) are
-- flagged as suspect legacy migration defaults, and dates
-- pre-dating the customer's own join date are flagged as
-- referential integrity violations. Both conditions render
-- the open date unreliable for tenure calculations.
-- A correlated subquery against raw.customers retrieves
-- the earliest valid join date per customer for the
-- second condition. The CTE output is aliased as pm to
-- allow correct resolution of the customer_id reference
-- inside the correlated subquery.

WITH product_mapping AS (
    SELECT
        customer_id,
        product_name,
        open_date,
        product_status,
        CASE
            WHEN UPPER(LTRIM(RTRIM(product_name))) IN (
                'CHEQUE ACCOUNT', 'CHEQUE ACC', 'CA')
                THEN 'Cheque Account'
            WHEN UPPER(LTRIM(RTRIM(product_name))) IN (
                'SAVINGS ACCOUNT', 'SAVINGS ACC', 'SA')
                THEN 'Savings Account'
            WHEN UPPER(LTRIM(RTRIM(product_name))) IN (
                'HOME LOAN', 'HOME LN', 'HL')
                THEN 'Home Loan'
            WHEN UPPER(LTRIM(RTRIM(product_name))) IN (
                'CREDIT CARD', 'CREDIT CRD', 'CC')
                THEN 'Credit Card'
            WHEN UPPER(LTRIM(RTRIM(product_name))) IN (
                'PERSONAL LOAN', 'PERSONAL LN', 'PL')
                THEN 'Personal Loan'
            ELSE 'Unknown'
        END AS product_name_clean
    FROM raw.products
)

SELECT
    pm.customer_id,
    pm.product_name_clean                               AS product_name,

    -- Open date: converted to DATE where parseable
    TRY_CONVERT(DATE, pm.open_date)                    AS open_date,

    -- Open date validity flag
    -- Flags dates before bank inception (2015-01-01) and
    -- dates pre-dating the customer's own join date.
    -- Both conditions represent referential integrity
    -- violations and are excluded from tenure calculations.
    -- CTE output aliased as pm to allow correct resolution
    -- of customer_id inside the correlated subquery.
    CASE
        WHEN TRY_CONVERT(DATE, pm.open_date) IS NULL
            THEN 0
        WHEN TRY_CONVERT(DATE, pm.open_date) < '2015-01-01'
            THEN 0
        WHEN TRY_CONVERT(DATE, pm.open_date) < (
            SELECT MIN(TRY_CONVERT(DATE, c.join_date))
            FROM raw.customers c
            WHERE c.customer_id = pm.customer_id
            AND TRY_CONVERT(DATE, c.join_date) IS NOT NULL
            AND TRY_CONVERT(DATE, c.join_date) <= '2024-12-31'
        )   THEN 0
        ELSE 1
    END                                                  AS is_valid_open_date,

    -- Product status: nulls imputed as Unknown
    ISNULL(pm.product_status, 'Unknown')               AS product_status

INTO staging.products
FROM product_mapping pm;

-- ============================================================
-- SECTION 3: STAGING.ACTIVITY
-- ============================================================

IF OBJECT_ID('staging.activity', 'U') IS NOT NULL
    DROP TABLE staging.activity;

SELECT
    a.customer_id,

    -- Balance: retained as-is including negative values
    -- Negative balances represent valid overdraft positions
    -- in a retail banking context and are not corrected.
    -- The extreme outlier (R4.2M) is flagged separately
    -- below rather than removed, preserving the record
    -- while allowing it to be toggled in Power BI analysis.
    ROUND(TRY_CONVERT(FLOAT,
        a.avg_monthly_balance), 2)                      AS avg_monthly_balance,

    -- Outlier balance flag
    -- The R4.2M balance is a statistical outlier that will
    -- skew mean-based calculations. Flagging rather than
    -- removing preserves the record for inclusion in aggregations.
    CASE
        WHEN TRY_CONVERT(FLOAT,
            a.avg_monthly_balance) > 1000000 THEN 1
        ELSE 0
    END                                                  AS is_outlier_balance,

    -- Balance tier for segmentation analysis
    CASE
        WHEN TRY_CONVERT(FLOAT,
            a.avg_monthly_balance) < 0       THEN 'Overdrawn'
        WHEN TRY_CONVERT(FLOAT,
            a.avg_monthly_balance) < 10000   THEN 'R0 - R9,999'
        WHEN TRY_CONVERT(FLOAT,
            a.avg_monthly_balance) < 50000   THEN 'R10,000 - R49,999'
        WHEN TRY_CONVERT(FLOAT,
            a.avg_monthly_balance) < 200000  THEN 'R50,000 - R199,999'
        ELSE                                      'R200,000 & above'
    END                                                  AS balance_tier,

    -- Credit score: null values retained as NULL
    -- Credit score is a risk-sensitive field. Imputing
    -- a value could misrepresent a customer's risk profile
    -- and introduce bias into retention scoring models.
    -- Double conversion handles decimal string storage
    -- from the source system (e.g. "518.0")
    TRY_CONVERT(INT, TRY_CONVERT(FLOAT,
        a.credit_score))                                AS credit_score,

    -- Credit band for segmentation analysis
    -- Aligned to South African credit scoring ranges
    CASE
        WHEN TRY_CONVERT(FLOAT,
            a.credit_score) IS NULL                    THEN 'Unknown'
        WHEN TRY_CONVERT(INT, TRY_CONVERT(FLOAT,
            a.credit_score)) < 450                     THEN 'Poor'
        WHEN TRY_CONVERT(INT, TRY_CONVERT(FLOAT,
            a.credit_score)) < 600                     THEN 'Fair'
        WHEN TRY_CONVERT(INT, TRY_CONVERT(FLOAT,
            a.credit_score)) < 700                     THEN 'Good'
        WHEN TRY_CONVERT(INT, TRY_CONVERT(FLOAT,
            a.credit_score)) < 750                     THEN 'Very Good'
        ELSE                                                'Excellent'
    END                                                  AS credit_band,

    -- Transaction count: cast to INT
    TRY_CONVERT(INT,
        a.num_transactions_3m)                          AS num_transactions_3m,

    -- Active member flag: cast to BIT
    TRY_CONVERT(BIT, a.is_active_member)               AS is_active_member,

    -- Last transaction date: converted to DATE
    TRY_CONVERT(DATE, a.last_txn_date)                 AS last_txn_date,

    -- Last transaction date validity flag
    -- Dates predating the customer's join date are
    -- impossible and are excluded from recency calculations
    CASE
        WHEN TRY_CONVERT(DATE, a.last_txn_date) IS NULL
            THEN 0
        WHEN TRY_CONVERT(DATE, a.last_txn_date) < (
            SELECT MIN(TRY_CONVERT(DATE, c.join_date))
            FROM raw.customers c
            WHERE c.customer_id = a.customer_id
            AND TRY_CONVERT(DATE, c.join_date) IS NOT NULL
            AND TRY_CONVERT(DATE, c.join_date) <= '2024-12-31'
        )   THEN 0
        ELSE 1
    END                                                  AS is_valid_last_txn,

    -- Churned flag: cast to BIT
    TRY_CONVERT(BIT, a.churned)                        AS churned,

    -- Churn date: NULL for non-churned customers
    -- This is intentional — NULL here means retained,
    -- not missing data
    TRY_CONVERT(DATE, a.churn_date)                    AS churn_date

INTO staging.activity
FROM raw.activity a
WHERE EXISTS (
    SELECT 1
    FROM raw.customers c
    WHERE c.customer_id = a.customer_id
);

SELECT * FROM staging.activity

-- ============================================================
-- SECTION 4: VALIDATION
-- ============================================================

-- Row count validation across all three staging tables
-- Cross-referenced against raw counts to confirm no
-- unintended row loss during transformation
SELECT
    'staging.customers' AS table_name,
    COUNT(*)            AS row_count
FROM staging.customers
UNION ALL
SELECT
    'staging.products',
    COUNT(*)
FROM staging.products
UNION ALL
SELECT
    'staging.activity',
    COUNT(*)
FROM staging.activity;

-- Province standardisation validation
-- Confirms all 26 raw variants have collapsed to
-- 9 clean values with no residual Unknown values
SELECT
    province,
    COUNT(*) AS count
FROM staging.customers
GROUP BY province
ORDER BY count DESC;

-- Gender standardisation validation
SELECT
    gender,
    COUNT(*) AS count
FROM staging.customers
GROUP BY gender
ORDER BY count DESC;

-- Product name standardisation validation
SELECT
    product_name,
    COUNT(*) AS count
FROM staging.products
GROUP BY product_name
ORDER BY count DESC;

-- Duplicate resolution validation
-- Confirms no CustomerID appears more than once
-- in staging.customers
SELECT
    customer_id,
    COUNT(*) AS occurrence_count
FROM staging.customers
GROUP BY customer_id
HAVING COUNT(*) > 1;

-- BIT column validation
-- Confirms is_active_member and churned contain
-- only 0 and 1 values after casting
SELECT
    is_active_member,
    COUNT(*) AS count
FROM staging.activity
GROUP BY is_active_member
ORDER BY is_active_member;

SELECT
    churned,
    COUNT(*) AS count
FROM staging.activity
GROUP BY churned
ORDER BY churned;